# Generated by Django 5.2 on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0055_user_jellyfin_mark_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="jellyfin_url",
            field=models.CharField(
                blank=True,
                help_text="Jellyfin server URL (e.g. http://localhost:8096)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="jellyfin_api_key",
            field=models.CharField(
                blank=True,
                help_text="Jellyfin API key for outbound requests",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="jellyfin_user_id",
            field=models.CharField(
                blank=True,
                help_text="Jellyfin user ID for play URLs",
                max_length=255,
            ),
        ),
    ]
