# Generated by Django 5.2.14 on 2026-06-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_user_jellyfin_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='download_client',
            field=models.CharField(blank=True, help_text='Download client type (e.g. transmission)', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='download_client_pass',
            field=models.CharField(blank=True, help_text='Download client password', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='download_client_url',
            field=models.CharField(blank=True, help_text='Download client URL (e.g. http://localhost:9091)', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='download_client_user',
            field=models.CharField(blank=True, help_text='Download client username', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='download_default_path',
            field=models.CharField(blank=True, help_text='Default download directory path', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='download_min_seeders',
            field=models.IntegerField(default=0, help_text='Minimum seeders for instant download'),
        ),
        migrations.AddField(
            model_name='user',
            name='download_prefer_best_quality',
            field=models.BooleanField(default=True, help_text='True = best quality score, False = most seeders'),
        ),
        migrations.AddField(
            model_name='user',
            name='download_prefer_verified',
            field=models.BooleanField(default=False, help_text='Prefer TorrentClaw verified releases'),
        ),
        migrations.AddField(
            model_name='user',
            name='download_preferred_audio',
            field=models.CharField(blank=True, help_text='Preferred audio format for instant download', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='download_preferred_codec',
            field=models.CharField(blank=True, help_text='Preferred codec for instant download', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='download_preferred_hdr',
            field=models.CharField(blank=True, help_text='Preferred HDR type for instant download', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='download_preferred_quality',
            field=models.CharField(default='1080p', help_text='Preferred quality for instant download', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='torrentclaw_api_key',
            field=models.CharField(blank=True, help_text='TorrentClaw API key for torrent search', max_length=255),
        ),
    ]
