# Generated by Django 5.2.14 on 2026-06-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_user_download_client_user_download_client_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='download_prefer_efficient',
            field=models.BooleanField(default=False, help_text='Pick smallest good-quality torrent (quality per GB ratio)'),
        ),
    ]
